services:
  postgres:
    image: postgres:17-alpine
    container_name: anime_db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: anime_db
    volumes:
      - pg_data:/var/lib/postgresql/data

  flyway:
    image: flyway/flyway
    container_name: anime_flyway
    command: -connectRetries=60 migrate
    environment:
      FLYWAY_URL: jdbc:postgresql://postgres:5432/anime_db
      FLYWAY_USER: ${POSTGRES_USER}
      FLYWAY_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./sql:/flyway/sql
    depends_on:
      - postgres

  app:
    build: .
    container_name: anime_app
    env_file:
      - .env
    depends_on:
      - postgres
      - flyway
    volumes:
      - ./images:/opt/anime-images
    ports:
      - "8080:8080"

volumes:
  pg_data:
